# Generated by Django 4.2.2 on 2023-08-20 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandeurs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacts',
            new_name='ContactModel',
        ),
        migrations.RenameModel(
            old_name='Extraitabobos',
            new_name='ExtraitModel',
        ),
        migrations.RenameModel(
            old_name='Reclamation',
            new_name='ReclamationModel',
        ),
        migrations.RenameModel(
            old_name='Validation',
            new_name='ValidationModel',
        ),
    ]
