# Generated by Django 4.2.2 on 2023-08-20 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demandeurs', '0002_rename_contacts_contactmodel_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='extraitmodel',
            old_name='exemplaire',
            new_name='Photocopie_d_extrait',
        ),
    ]
